####################################################################################################
#####                              TX Ultimate Easy for ESPHome                                #####
#####                  Repository: https://github.com/edwardtfn/TX-Ultimate-Easy               #####
####################################################################################################
##### Purpose: ESPHome Core - Add-on - BLE Proxy (REMOVED)                                     #####
####################################################################################################
##### Author: edwardtfn - https://github.com/edwardtfn - https://buymeacoffee.com/edwardfirmo  #####
####################################################################################################
##### REMOVAL NOTICE:                                                                          #####
##### This package has been removed. Please update your configuration.                        #####
##### Add BLE proxy functionality directly in your YAML configuration instead:                #####
#####   bluetooth_proxy:                                                                       #####
####################################################################################################
---
# Trigger the error at compile time
script:
  - id: force_compilation_error
    then:
      - lambda: |-
          #error "The package TX-Ultimate-Easy-ESPHome_addon_ble_proxy.yaml has been removed." \
                 "Please remove this package from your configuration and add" \
                 "'bluetooth_proxy:' directly to your YAML instead."
...
