####################################################################################################
#####                              TX Ultimate Easy for ESPHome                                #####
#####                  Repository: https://github.com/edwardtfn/TX-Ultimate-Easy               #####
####################################################################################################
##### Purpose: ESPHome Standard (non-essential, but recommended packages)                      #####
####################################################################################################
##### Author: edwardtfn - https://github.com/edwardtfn - https://buymeacoffee.com/edwardfirmo  #####
####################################################################################################
##### NOTE:                                                                                    #####
##### - Make changes ONLY if absolutely necessary and you have the required knowledge.         #####
##### - For normal system use, modifications to this file are NOT required.                    #####
####################################################################################################
---
packages:
  # yamllint disable rule:colons
  standard_hw_relays:    !include TX-Ultimate-Easy-ESPHome_standard_hw_relays.yaml
  standard_hw_vibration: !include TX-Ultimate-Easy-ESPHome_standard_hw_vibration.yaml
  standard_media_player: !include TX-Ultimate-Easy-ESPHome_standard_media_player.yaml
  # yamllint enable rule:colons
...
